DROP TABLE IF EXISTS Transactions;
DROP TABLE IF EXISTS ScoreHistory;
DROP TABLE IF EXISTS Cards;
DROP TABLE IF EXISTS Inquiries;
DROP TABLE IF EXISTS Marks;
DROP TABLE IF EXISTS Merchants;
DROP TABLE IF EXISTS Notifications;
